### ISSUE TITLE
tcp socket not listening when hiddennode

### ISSUE THREAD

**Issue by SanyaNet** [RetroShare/RetroShare#170]
revision 0.6.0 RC2.8551

1) tcp socket does not start listening unless I run startup wizard from main options and select manually forwarded port option.
2) after this "test hidden service" input port section might dissapear
3) after programm restart all the settings are reset. so I have to configure hidden address and it's port again in the options

os: winxp

apparently it doesn't even try to connect to other peers over tcp port. 
I don't see any outgoing tcp connections through tor proxy.

**Comment by electron128** [comment]
The TCP socket does listen for me with latest sources. I will not test with old version.
If the node is a hidden node, it should not be possible to change the network mode to "manually forwarded port". I fixed this in 4b8476725003a23161d7c0eacc3f3ab0fab82fa6.

> apparently it doesn't even try to connect to other peers over tcp port. 

Making **outgoing** connections from a hidden node requires these things:
- Tor/I2P is working and RS is properly configured
- the node to connect to must be a hidden node

Note: normal nodes can connect to hidden nodes if they have configured the Tor/I2P Proxy. It will then appear as an **incoming** connection for the hidden node.

**Comment by SanyaNet** [comment]
it does not work. if retroshare runs as a service it should listen the tcp port so to accept connections from tor. in rc2.8551 it listen only udp ports. 
Thus nor other party would be able to connect through tor, nor a hidden node would be able to connect to non-hidden node because tcp ports are not listening. 
There are some bugs around it. 

"1) tcp socket does not start listening unless I run startup wizard from main options and select manually forwarded port option.
2) after this "test hidden service" input port section might dissapear
3) after programm restart all the settings are reset. so I have to configure hidden address and it's port again in the options"

**Comment by cavebeat** [comment]
v0.6.0 RC2.8551 is already dated, may i close it or is the bug still open?

**Comment by sanyanet2** [comment]
Hi, Its me again. 
Version 0.6.4 91634ba6 Qt4

this bug still happen. I choose hidden node configuration, then set up tor and tor proxy.
Tor socks connection is ok. Incoming tor connections are ok. 
But today when I started the node I see that incoming tor connections are not ok. 
The tor is running fine. When I look at my firewall I see that retroshare node only listen on UDP port
Incoming tor connections reach the system, but retroshare node does not listen on this port for TCP

When I start normal node I could see that both TCP and UDP sockets are listening.

**Comment by sanyanet2** [comment]
Huh, seems like I got what was the issue. I have 2 network interfaces. 
Looks like retroshare was listening on 127.0.0.1
while tor is directed to 192.0.0.1  
I've added a fowarding rule from one interface to another and it seems to work now.
Will see if I have this issue again. 

Still it would be nice to set localhost interface from retroshare client itself.
